# Generated by Django 5.2.3 on 2025-07-04 11:55

import accounts.utils.image_upload
import core.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('image', models.ImageField(blank=True, help_text='Upload your image...', null=True, upload_to=accounts.utils.image_upload.USER_DIRECTORY_PATH, validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE], verbose_name='Image')),
                ('user_id', models.CharField(db_index=True, editable=False, max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='User ID')),
                ('name', models.CharField(help_text='Enter your name...', max_length=60, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Enter your email...', max_length=80, unique=True, validators=[core.utils.VALIDATE_EMAIL, django.core.validators.MinLengthValidator(10)], verbose_name='Email')),
                ('number', models.CharField(blank=True, db_index=True, help_text='Enter your number...', max_length=20, null=True, unique=True, validators=[core.utils.VALIDATE_PHONE_NUMBER, django.core.validators.MinLengthValidator(5)], verbose_name='Number')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Enter your gender...', max_length=20, null=True, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter your birth date...', null=True, verbose_name='Birth Date')),
                ('country', models.CharField(blank=True, help_text='Enter your country', max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Country')),
                ('signature', models.CharField(blank=True, help_text='Enter your signature...', max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Signature')),
                ('role', models.CharField(blank=True, choices=[('crypto', 'Crypto'), ('e-commerce', 'E-commerce'), ('admin', 'Admin')], help_text='Enter your role...', max_length=20, null=True, verbose_name='Role')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_block', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='accounts_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='accounts_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('user_agent', models.TextField()),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
