version: '3.9'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    networks:
      - pngnet
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    env_file:
      - .env
      - ./backend/.env
    depends_on:
      - redis
      - postgres
    networks:
      - pngnet
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  redis:
    image: redis:7-alpine
    networks:
      - pngnet

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pngnet

  nginx:
    image: nginx:1.24-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/dist:/usr/share/nginx/html:ro
      - ./backend/static:/backend/static:ro
      - ./backend/media:/backend/media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - pngnet

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  pngnet:
    driver: bridge
