version: '3.9'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - devnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - devnet

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
