# Generated by Django 5.2.3 on 2025-07-04 11:55

import configuration.utils.logo_upload
import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Upload your logo...', null=True, upload_to=configuration.utils.logo_upload.LOGO_DIRECTORY_PATH, validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE], verbose_name='Logo')),
                ('description', models.TextField(blank=True, help_text='Enter your description...', max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Footer description')),
            ],
            options={
                'verbose_name': 'Footer Logo',
                'verbose_name_plural': 'Footer Logo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Upload your logo...', null=True, upload_to=configuration.utils.logo_upload.LOGO_DIRECTORY_PATH, validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE], verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
                'ordering': ['-id'],
            },
        ),
    ]
