# Generated by Django 5.2.3 on 2025-07-04 12:15

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, help_text='Enter your address...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Address')),
                ('email', models.EmailField(blank=True, help_text='Enter your email address...', max_length=180, null=True, validators=[core.utils.VALIDATE_EMAIL], verbose_name='Email')),
                ('number', models.CharField(blank=True, help_text='Enter your number...', max_length=20, null=True, validators=[core.utils.VALIDATE_PHONE_NUMBER], verbose_name='Number')),
            ],
        ),
    ]
