# Generated by Django 5.2.3 on 2025-07-04 12:41

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_officialinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload your about image...', null=True, upload_to='about', validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE], verbose_name='About Image')),
                ('title', models.TextField(blank=True, help_text='Enter your about title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='About Title')),
                ('description', models.TextField(blank=True, help_text='Enter your about description...', max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='About description')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, help_text='Upload a promotional banner video (MP4, AVI, etc).', null=True, upload_to='banner', verbose_name='Banner Video')),
                ('title', models.TextField(blank=True, help_text='Enter your banner title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Banner Title')),
                ('sub_title', models.TextField(blank=True, help_text='Enter your banner title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Banner Sub-Title')),
                ('description', models.TextField(blank=True, help_text='Enter your banner description...', max_length=10000, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Banner description')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload your service image...', null=True, upload_to='services', validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE], verbose_name='Service Image')),
                ('title', models.TextField(blank=True, help_text='Enter your service title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Service Title')),
                ('description', models.TextField(blank=True, help_text='Enter your service description...', max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Service description')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload your team image...', null=True, upload_to='team/', validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE], verbose_name='Team Image')),
                ('title', models.CharField(blank=True, help_text='Enter your team title...', max_length=180, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Team Title')),
                ('description', models.TextField(blank=True, help_text='Enter your team description...', max_length=10000, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Team description')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload your whychooseus image...', null=True, upload_to='whychooseus', validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE], verbose_name='WhyChooseUs Image')),
                ('title', models.TextField(blank=True, help_text='Enter your whychooseus title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='WhyChooseUs Title')),
                ('description', models.TextField(blank=True, help_text='Enter your whychooseus description...', max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='WhyChooseUs description')),
            ],
        ),
        migrations.AlterModelOptions(
            name='officialinfo',
            options={'ordering': ['-id'], 'verbose_name': 'Official Info', 'verbose_name_plural': 'Official Info'},
        ),
    ]
