# Generated by Django 5.2.3 on 2025-07-04 14:03

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_about_banner_services_team_whychooseus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseus',
            name='sub_image',
            field=models.ImageField(blank=True, help_text='Upload your whychooseus-sub image...', null=True, upload_to='whychooseus', validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE], verbose_name='WhyChooseUs Sub-Image'),
        ),
    ]
