# Generated by Django 5.2.4 on 2025-07-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_whychooseus_sub_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='url',
            field=models.URLField(blank=True, help_text='Enter your team URL...', max_length=500, null=True, verbose_name='Team URL'),
        ),
    ]
