# Generated by Django 5.2.4 on 2025-07-11 22:51

import core.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_team_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload your crypto trades image...', null=True, upload_to='crypto-trades/images/', validators=[core.utils.VALIDATE_IMAGE_EXTENSION, core.utils.VALIDATE_IMAGE_SIZE], verbose_name='Crypto Trades Image')),
                ('video', models.FileField(blank=True, help_text='Upload your crypto trades video...', null=True, upload_to='crypto-trades/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])], verbose_name='Crypto Trades Video')),
                ('title', models.CharField(blank=True, help_text='Enter your crypto trades title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Crypto Trades Title')),
                ('description', models.TextField(blank=True, help_text='Enter your crypto trades description...', max_length=5000, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Crypto Trades Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when this trade was created', verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTradesSubTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, help_text='Enter your crypto trades sub title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Sub Title')),
                ('trade', models.ForeignKey(help_text='Select the parent crypto trade...', on_delete=django.db.models.deletion.CASCADE, related_name='sub_titles', to='configuration.cryptotrades', verbose_name='Parent Crypto Trade')),
            ],
        ),
    ]
