# Generated by Django 5.2.4 on 2025-07-11 23:17

import core.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_alter_cryptotrades_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload your market updates image...', null=True, upload_to='market-updates/images/', validators=[core.utils.VALIDATE_IMAGE_EXTENSION], verbose_name='Market Updates Image')),
                ('video', models.FileField(blank=True, help_text='Upload your market updates video...', null=True, upload_to='market-updates/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])], verbose_name='Market Updates Video')),
                ('title', models.CharField(blank=True, help_text='Enter your market updates title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Market Updates Title')),
                ('description', models.TextField(blank=True, help_text='Enter your market updates description...', max_length=5000, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Market Updates Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when this trade was created', verbose_name='Created At')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCommoditiesTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload your stock commodities trades image...', null=True, upload_to='stock-commodities-trades/images/', validators=[core.utils.VALIDATE_IMAGE_EXTENSION], verbose_name='Stock Commodities Trades Image')),
                ('video', models.FileField(blank=True, help_text='Upload your stock commodities trades video...', null=True, upload_to='stock-commodities-trades/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])], verbose_name='Stock Commodities Trades Video')),
                ('title', models.CharField(blank=True, help_text='Enter your stock commodities trades title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Stock Commodities Trades Title')),
                ('description', models.TextField(blank=True, help_text='Enter your stock commodities trades description...', max_length=5000, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Stock Commodities Trades Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when this trade was created', verbose_name='Created At')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='cryptotrades',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='MarketUpdatesSubTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, help_text='Enter your market updates sub title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Sub Title')),
                ('market_updates', models.ForeignKey(help_text='Select the parent market updates...', on_delete=django.db.models.deletion.CASCADE, related_name='sub_titles', to='configuration.marketupdates', verbose_name='Parent market updates')),
            ],
        ),
        migrations.CreateModel(
            name='StockCommoditiesTradesSubTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, help_text='Enter your stock commodities trades sub title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Sub Title')),
                ('stock_commodities_trades', models.ForeignKey(help_text='Select the parent stock commodities trades...', on_delete=django.db.models.deletion.CASCADE, related_name='sub_titles', to='configuration.stockcommoditiestrades', verbose_name='Parent Stock Commodities Trades')),
            ],
        ),
    ]
