# Generated by Django 5.2.4 on 2025-07-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_marketupdates_stockcommoditiestrades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Upload your e-commerce video...', upload_to='e-commerce/videos/', verbose_name='E-commerce Video')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when this education video was created', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'E-commerce Video',
                'verbose_name_plural': 'E-commerce Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Upload your education video...', upload_to='education/videos/', verbose_name='Education Video')),
                ('status', models.CharField(choices=[('advance', 'Advance'), ('beginner', 'Beginner')], help_text='Select the difficulty level of this video.', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when this education video was created', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Education Video',
                'verbose_name_plural': 'Education Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
