# Generated by Django 5.2.4 on 2025-07-12 05:19

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_ecommercevideo_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload your image...', null=True, upload_to='e-commerce-service/', validators=[core.utils.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
                ('title', models.CharField(blank=True, help_text='Enter your title...', max_length=180, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title')),
                ('price', models.CharField(blank=True, help_text='Enter your service price...', max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when this education video was created', verbose_name='Created At')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
