# Generated by Django 5.2.4 on 2025-07-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('e-commerce', 'E-Commerce')], default='crypto', max_length=20),
        ),
    ]
